### ISSUE TITLE
State of CSS 2020

### ISSUE THREAD

**Issue by thiagoloal** [Devographics/locale-pt-BR#3]
List of sections that need translations:
- [x] [**state_of_css_2020.yml**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_css_2020.yml)
  - [x] Introduction
  - [x] Tshirt
  - [x] Sections Introductions
  - [x] Notes
  - [x] Awards
  - [x] Conclusion
  - [x] Picks

**Comment by HakaCode** [comment]
Opah Traduzindo este agora!

**Comment by HakaCode** [comment]
Done
