### ISSUE TITLE
State of JS 2020

### ISSUE THREAD

**Issue by thiagoloal** [Devographics/locale-pt-BR#5]
Lista de seções que necessitam de traduções  para [State of JS 2020](https://2020.stateofjs.com/en-US/)

### Results
- [x] [**state_of_js_2020.yml**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_js_2020.yml)
  - [x] General
  - [x] Introduction
  - [x] Tshirt
  - [x] Sections Introductions
  - [x] Notes
  - [x] Awards
  - [x] Conclusion
  - [x] Picks

### Survey
- [x] [**state_of_js_2020_survey**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_js_2020_survey)
  - [x] General

**Comment by HakaCode** [comment]
@thiagoloal traduzo este agora.

**Comment by HakaCode** [comment]
Done
