### ISSUE TITLE
Convite Discord Inválido

### ISSUE THREAD

**Issue by brunorrr** [Devographics/locale-pt-BR#50]
Olá,

gostaria de participar do processo de tradução, porém, o link do Discord passado por vocês não é válido, poderiam gerar outro? ou indicar oque posso fazer? Obrigado.

**Comment by the-physicist** [comment]
Olá, @brunorrr, segue um novo link de convite: https://discord.gg/trhgZaaF

**Comment by brunorrr** [comment]
Obrigado.
