### ISSUE TITLE
State of CSS 2021

### ISSUE THREAD

**Issue by thiagoloal** [Devographics/locale-pt-BR#6]
Lista de seções que necessitam de traduções  para [State of CSS 2021](https://2021.stateofcss.com/en-US/)

### Results
- [ ] [**state_of_css_2021_results.yml**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_css_2021_results.yml)
  - [x] Introduction
  - [ ] Tshirt
  - [ ] Sections Introductions
  - [ ] Charts
  - [ ] Notes
  - [ ] Awards
  - [ ] Conclusion
  - [ ] Picks

### Survey
- [ ] [**state_of_css_2021_survey**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_css_2021_survey.yml)
  - [ ] General

**Comment by HakaCode** [comment]
@the-physicist podemos fechar esta issue, visto que ja foi feito merge?

**Comment by the-physicist** [comment]
@HakaCode obrigado por lembrar! Feito.
